### ISSUE TITLE
Mac version Hugin cannot send messages properly

### ISSUE THREAD

**Issue by Gegegega** [kryptokrona/hugin-desktop#113]
I have installed the latest Hugin Mac client on an Apple M2 with an OS version of 14.0. 

When I first logged into Hugin to send messages, it was normal. But when I used it the next day, I couldn't send messages, and when an error prompt popped up, clicking optimization had no effect, and the error continued to pop up. At this point, the network node displays normal, but the block height is 0, the wallet balance is also normal, and it also shows that it has been synchronized.

The problem has been ongoing for several days, please fix this bug as soon as possible. The attachment is three screenshots.

<img width="386" alt="1" src="https://github.com/kryptokrona/hugin-desktop/assets/154481985/51298781-7c68-4841-83d7-2d5b989062ae">
<img width="861" alt="2" src="https://github.com/kryptokrona/hugin-desktop/assets/154481985/bc68dcea-fa27-4764-b61c-3daac104acbc">
<img width="986" alt="3" src="https://github.com/kryptokrona/hugin-desktop/assets/154481985/63fc1cce-27b5-47ea-8521-5260ffabc44c">

**Comment by n9lsjr** [comment]
It looks like your node connection does not work! First, you could test another node and see if a correct height is displayed. If that does not work, go to settings -> Rescan wallet -> and pick a height to rescan from.

**Comment by n9lsjr** [comment]
It also seems like your balance is quite low and you may not have enough XKR inputs to send more messages with until the next day. Try sending 1XKR to your hugin and test it again if the node is working correctly and shows a normal block height
