### ISSUE TITLE
[Bug]: Close button does not work (win11)

### ISSUE THREAD

**Issue by DanielBoye** [kryptokrona/hugin-desktop#39]
### Contact Details

danielboye888@gmail.com

### What happened?

The buttons do not light up when I hover over it. I can not close the program, or get the "more" menu if we can call it that. 

![image](https://user-images.githubusercontent.com/83395536/199947375-93e9840a-d385-45ad-9914-972b191a5f1d.png)

The buttons in question are these two. I tested the program on my laptop that is running Windows 11. 

I am running 0.1.3, not 0.1.0 but that is the only version I can choose. 

### Version

1.0.0 (Default)

### On what OS are you experience the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DanielBoye** [comment]
Or I could just have fat fingers, idk

**Comment by n9lsjr** [comment]
Thanks! Swepool fixed 👍 https://github.com/kryptokrona/hugin-desktop/commit/7123588b69873003fac02068d9e59e99ab250035
