### ISSUE TITLE
[Bug]: send message failed。

### ISSUE THREAD

**Issue by bingo1168** [kryptokrona/hugin-desktop#41]
### Contact Details

383390710@qq.com

### What happened?

A bug happened!    when need opmitize？  after optimize what happend？

I can receive your message。  but not reply。  say Failed to send
### Version

1.0.0 (Default)

### On what OS are you experience the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by n9lsjr** [comment]
We have improved the optimize since this. Closing this issue. Thanks for the feedback 👍
