### ISSUE TITLE
[Bug]: hugin desktop wallet sync from height 900000，sync to 988754 stoped。

### ISSUE THREAD

**Issue by bingo1168** [kryptokrona/hugin-desktop#42]
### Contact Details

383390710@qq.com

### What happened?

A bug happened!

### Version

1.0.0 (Default)

### On what OS are you experience the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Reidjoss** [comment]
![image](https://user-images.githubusercontent.com/2069259/202666566-2133d192-3085-4b98-a059-f8dbeb8c60e3.png)

**Comment by bingo1168** [comment]
I can't understand you saying.this need fix?&nbsp; &nbsp;problem with block?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月18日(星期五) 下午5:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kryptokrona/hugin-desktop] [Bug]: hugin desktop wallet sync from height 900000，sync to 988754 stoped。 (Issue #42)
