### ISSUE TITLE
[Bug]: Slow transition between views

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-desktop#44]
### What happened?

Enough ms to make it feel slow while switching views. It feels like it's 1000 ms, need to go under 400 ms.

### Version

1.0.0 (Default)

### On what OS are you experience the problem on?

Mac OS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by n9lsjr** [comment]
Also fixed 👍
