### ISSUE TITLE
[Bug]: loss message

### ISSUE THREAD

**Issue by bingo1168** [kryptokrona/hugin-desktop#45]
### What happened?

![InkedSnap6](https://user-images.githubusercontent.com/117485053/200745841-96c23ed8-6217-4f63-831a-e99296091175.jpg)

![微信图片_20221109132237](https://user-images.githubusercontent.com/117485053/200745933-e7a145d1-25b4-41e3-8cb7-e9284689a4b6.jpg)

the message loss。

### Version

1.0.0 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by n9lsjr** [comment]
This is not a desktop bug, the message has been removed from the mempool and the mobile can't find it. This will get better in the future.

**Comment by bingo1168** [comment]
This is not scientific, because you send information to the other party is not necessarily real-time online, more than 24 hours do not log in often things, as text information, saving does not need too much space, but setting a post-reading burning function is necessary, such as automatic post-reading burning, or readers manual destruction, or give a setting, set up post-reading burning, no matter what information, after reading the information disappears from memory。
![Snap3](https://user-images.githubusercontent.com/117485053/203472903-e697c759-610e-41e2-b2ce-4ede6f7156aa.jpg)

or right click can copy/reply/delete/post-reading burning     is ok.

**Comment by bingo1168** [comment]
This is not scientific, because you send information to the other party is not necessarily real-time online, more than 24 hours do not log in often things, as text information, saving does not need too much space, but setting a post-reading burning function is necessary, such as automatic post-reading burning, or readers manual destruction, or give a setting, set up post-reading burning, no matter what information, after reading the information disappears from memory。
or right click can copy/reply/delete/post-reading burning     is ok.
![Snap3](https://user-images.githubusercontent.com/117485053/203472903-e697c759-610e-41e2-b2ce-4ede6f7156aa.jpg)
