### ISSUE TITLE
[Bug]: desktop audio or video failed

### ISSUE THREAD

**Issue by bingo1168** [kryptokrona/hugin-desktop#46]
### What happened?

![微信图片_20221109133355](https://user-images.githubusercontent.com/117485053/200747439-2d893b5b-5d7d-4b3a-8501-0b6f98d09263.jpg)

when i video to my friends。  he use hugin mobile.    he can receive the message.   when fix it on mobile?

### Version

1.0.0 (Default)

### On what OS are you experience the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by n9lsjr** [comment]
This is a mobile issue.

**Comment by n9lsjr** [comment]
Audio and Video calls are not implemented in the Mobile version. You can only call others with the new Hugin desktop.
