### ISSUE TITLE
Display "joined" when I'm currently in the group on the dashboard

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-desktop#67]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mjovanc** [comment]
<img width="552" alt="Skärmavbild 2022-11-21 kl  08 07 15" src="https://user-images.githubusercontent.com/33717111/202986670-161dbe03-317d-4953-83ec-00f0d7bae62c.png">

**Comment by n9lsjr** [comment]
Also fixed, it removes joined groups
