### ISSUE TITLE
Pressing the name of the group re-renders the chatlist

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-desktop#68]
### What happened?

When pressing the group name on the sidebar it re-renders the chatlist again. In DM chatlist it doesn't have this behavior. 

### Version

0.1.6 (Latest)

### On what OS are you experience the problem on?

Mac OS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by n9lsjr** [comment]
Fixed
