### ISSUE TITLE
Can't do video/voice call over different OS

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-desktop#78]
### What happened?

Can't do video/voice call over different OS.

### Version

0.1.7 (Latest)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by n9lsjr** [comment]
The problem seems to be with M1-to-M1 and / or Linux. We need to investigate this further

**Comment by n9lsjr** [comment]
This is now fixed 👍
