### ISSUE TITLE
Restoring account does not update my balance

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-desktop#79]
### What happened?

When taking my mnemonic seed from my other Hugin wallet account and restore this in another OS (Windows) it does not update my balance or is able to optimize. See picture:

![image](https://user-images.githubusercontent.com/33717111/205596622-3413b79a-841b-4c5e-a33b-675f8e643722.png)

### Version

0.1.7 (Latest)

### On what OS are you experience the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by n9lsjr** [comment]
Wrong blockheight 👍 Was not a bug
