### ISSUE TITLE
Make the "Optimize" button green instead of red

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-desktop#83]
### Description of feature request

```shell
Currently the optimize button is red, which might indicate something is currently wrong with the optimize function. Perhaps change this to green?
```
![Skärmavbild 2022-12-12 kl  01 15 44](https://user-images.githubusercontent.com/33717111/206937726-4b0e1e92-22eb-4a78-9349-996d3667ff81.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by n9lsjr** [comment]
Its red when you can't press it and the wallet thinks you are optimized :D
