### ISSUE TITLE
Login takes a very long time to process

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-desktop#92]
When logging in, it takes like 10 or more seconds to actually login which should be quick. But perhaps it's because it's waiting from response from the node before rendering the dashboard. Because as soon as the popup notification appears I'm logged in.

**Comment by n9lsjr** [comment]
This is probably not a bug. Could you provide a more accurate measurement using the performance.now() timer in node?  My tests give about 3 seconds.  And we have added a sleep of 2 seconds before startup as you can see right here: https://github.com/kryptokrona/hugin-desktop/blob/main/src/backend/electron.cjs#L575.  I will lower it to 500ms.

**Comment by Swepool** [comment]
Can it be related to checkNodeStatus() maybe ?

**Comment by n9lsjr** [comment]
Yes probably, if the node, internet access or computer is slow, it will prolong the login process

**Comment by Swepool** [comment]
We could restructure and move checkNode to dash, to get the feeling it's
quick :P and then prompt if no node. Not a huge issue tho.

Den lör 25 feb. 2023 kl 16:12 skrev n9lsjr ***@***.***>:

**Comment by n9lsjr** [comment]
That is true, we can probably move it without too much work and make it feel alot faster! 👍

**Comment by mjovanc** [comment]
Is this function asynchronous? If yes, it should not hinder. Right?

**Comment by n9lsjr** [comment]
Right now, the user is prompted to choose a working node before logging in. This was by design to streamline the login process and avoid some confusion when connecting to a bad node and not noticing. We can change this to pop up in the dashboard instead.

**Comment by mjovanc** [comment]
Alright, fine and dandy sir.
