### ISSUE TITLE
Can not open conversation, click a button on anything really to switch views or send a message

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-desktop#94]
### Contact Details

mjovanc@icloud.com

### What happened?

After starting up Hugin (0.2.2) and selecting groups, it seems like I'm locked. To reproduce the error:

1. Start Hugin
2. Send a youtube video in a group

Now Hugin is always locked for pressing any button or sending anything new in the group. Even after restart it is not working, but at least I can press buttons. But not see any messages or send a message to the current group. I added a screenshot to illustrate.

<img width="1407" alt="Skärmavbild 2023-04-10 kl  10 43 31" src="https://user-images.githubusercontent.com/33717111/230866767-ec68067a-3333-4929-8356-9a54eca1d633.png">

### Version

0.1.7 (Latest)

### On what OS are you experience the problem on?

Mac OS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by n9lsjr** [comment]
Fixed 👍
